name: Build and Deploy Spring Boot Jar

on:
  push:
    branches:
      - main # 远程只有一个main分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取 GitHub 仓库代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 配置 JDK 环境（如果用 Java 21/11，把 17 改掉即可）
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven # 如果项目用的是 Gradle，这里改成 gradle

      # 3. 赋予 mvnw 执行权限并打包 Jar
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4. 把打包好的 jar 包传输到服务器
      - name: Copy Jar to Server via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "target/*.jar,Dockerfile"      # Maven打包出来的路径，如果是Gradle填 build/libs/*.jar
          target: "/usr/web/backend"            # 服务器上存放 jar 包的文件夹路径
          strip_components: 1             # 传输时剥离 target 目录，只传输 jar 包本身

      # 服务器本地构建镜像并运行容器
      - name: Build Docker Image and Restart Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          envs: OSS_KEY_ID,OSS_KEY_SECRET,TPS_KEY # 必须声明：把 env 里的变量注入给 SSH script
          script: |
            cd /usr/web/backend
            
            # 构建镜像
            docker build -t gongsheng:2.0 .
            
            # 停止并删除旧容器
            docker stop gongsheng || true
            docker rm gongsheng || true
            
            # 运行新容器
            docker run -d -p 8080:8080 \
            -e SPRING_PROFILES_ACTIVE=prod \
            -e OSS_ACCESS_KEY_ID="$OSS_KEY_ID" \
            -e OSS_ACCESS_KEY_SECRET="$OSS_KEY_SECRET" \
            -e TPSApiKey="$TPS_KEY" \
            --network taiyidu \
            --restart always \
            --name gongsheng gongsheng:2.0
            
            # 删除构建以后原来的旧镜像
            docker image prune -f

        env:
            OSS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
            OSS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
            TPS_KEY: ${{ secrets.TPSAPIKEY }}